### ISSUE TITLE
Inlinescrollning i listan över personer att matcha

### ISSUE THREAD

**Issue by jongotlin** [kompisbyran/Kompisbyran#22]
Listan med personer att koppla kan bli väldigt lång. Därför behöver de två spalterna kunna scrollas separat för att kunna se personen man letar en kompis till.
<img width="1131" alt="screenshot 2015-12-06 16 04 47" src="https://cloud.githubusercontent.com/assets/165154/11613957/62dc4bb4-9c33-11e5-8471-953789e991b9.png">

**Comment by sirowl** [comment]
vad tror vi om att ha en (extremt simpelt) filter för varje lista också när vi ändå är i farten?

**Comment by jongotlin** [comment]
Det finns redan. Det är väldigt simpelt och tydligen lite buggigt om man klickar snabbt. Vad vill man mer ha med där? Åldersintervall, kön? @EmmaHammar 
<img width="536" alt="screenshot 2015-12-06 16 30 47" src="https://cloud.githubusercontent.com/assets/165154/11614062/bfa6ef4a-9c36-11e5-8ca0-48849ae03679.png">
